python prune.py --name vgg19 --ratio 0.99 --finetune
python prune.py --name vgg19 --ratio 0.98 --finetune
python prune.py --name vgg19 --ratio 0.95 --finetune
python prune.py --name vgg19 --ratio 0.90 --finetune
python prune.py --name vgg19 --ratio 0.85 --finetune
python prune.py --name vgg19 --ratio 0.80 --finetune
python prune.py --name vgg19 --ratio 0.75 --finetune
python prune.py --name vgg19 --ratio 0.70 --finetune
python prune.py --name vgg19 --ratio 0.65 --finetune
python prune.py --name vgg19 --ratio 0.60 --finetune
python prune.py --name vgg19 --ratio 0.50 --finetune